package br.com.plataformalancamentofinanceiro.enumeration;

public enum TipoCategoriaPessoaEnumeration {
	INSTITUICAO_FINANCEIRA,
    INSTITUICAO_EDUCACIONAL,
    ASSOCIACAO_RELIGIOSA,
    ALIMENTOS_RESTAURANTE,
    ALIMENTOS_LANCHONETE,
    ALIMENTOS_PADARIA,
    SUPERMERCADO,
    LOJA_DEPARTAMENTO,
    FORNECEDORA_SERVICOS_AGUA_ESGOTO,
    FORNECEDORA_SERVICOS_ENERGIA_ELETRICA,
    FORNECEDORA_SERVICOS_TELEFONIA_FIXA_INTERNET,
    FORNECEDORA_SERVICOS_TELEFONIA_MOVEL_INTERNET,
    FORNECEDORA_SERVICOS_LOTERICOS,
    COMERCIO_AMBULANTE,
    COMERCIO_TABACARIA;
}
