-- VERIFICAR TODOS OS BANCOS DE DADOS
SELECT DATNAME FROM PG_DATABASE WHERE DATISTEMPLATE = FALSE;

-- CIAR BANCO DE DADOS
CREATE DATABASE DB_FINANCEIRO_DESENVOLVIMENTO;
DROP DATABASE DB_FINANCEIRO_DESENVOLVIMENTO;

-- CONSULTAS
SELECT * FROM PUBLIC.TB_ATIVO_CIRCULANTE;